mavenAdditionalArgs: -Dannotation.failOnError=false
projectType: extension
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
    mavenAdditionalArgs: -DminVersion=4.3.0
  jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DminVersion=4.3.0
  jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -Dtest=none -DfailIfNoTests=false -DminVersion=4.6.0
mavenTool: "3.9.5"
